apiVersion: mesh.cellery.io/v1alpha1
kind: Composite
metadata:
  name: employee
  annotations:
    mesh.cellery.io/cell-image-org: cellery-samples
    mesh.cellery.io/cell-image-name: employee
    mesh.cellery.io/cell-image-version: 1.0.0
spec:
  servicesTemplates:
  - metadata:
      name: employee
    spec:
      autoscaling:
        policy:
          minReplicas: 0
          concurrency: 5
      container:
        image: docker.io/celleryio/sampleapp-employee
        env:
        - name: SALARY
          value: 'employee--salary-service-rev'
        ports:
        - containerPort: 8080
      servicePort: 80
  - metadata:
      name: salary
    spec:
      autoscaling:
        policy:
          minReplicas: 0
      container:
        image: docker.io/celleryio/sampleapp-salary
        ports:
        - containerPort: 8080
      servicePort: 80
  - metadata:
      name: debug
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/k8s-debug-tools
      servicePort: 80

