apiVersion: mesh.cellery.io/v1alpha1
kind: Cell
metadata:
  name: job-cell
  annotations:
    mesh.cellery.io/cell-image-org: cellery-samples
    mesh.cellery.io/cell-image-name: job-cell
    mesh.cellery.io/cell-image-version: 1.0.0
spec:
  gatewayTemplate:
    spec:
      type: Envoy
      http:
      - backend: hello
        context: /hello
  servicesTemplates:
  - metadata:
      name: job
    spec:
      container:
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      type: Job
  - metadata:
      name: debug
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/k8s-debug-tools
      servicePort: 80
