apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pet-store-orders
  namespace: default
  labels:
    app: pet-store
    service: orders
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: pet-store
        service: orders
    spec:
      containers:
        - image: celleryio/samples-pet-store-orders
          name: orders
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pet-store-orders
  namespace: default
  labels:
    app: pet-store
    service: orders
spec:
  selector:
    app: pet-store
    service: orders
  ports:
    - name: http
      port: 80
      targetPort: 80
