apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pet-store-portal
  namespace: default
  labels:
    app: pet-store
    service: portal
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: pet-store
        service: portal
    spec:
      containers:
        - image: celleryio/samples-pet-store-portal
          name: portal
          imagePullPolicy: IfNotPresent
          env:
            - name: PET_STORE_CELL_URL
              value: http://pet-be--gateway-service/controller
            - name: PORTAL_PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pet-store-portal
  namespace: default
  labels:
    app: pet-store
    service: portal
spec:
  selector:
    app: pet-store
    service: portal
  ports:
    - name: http
      port: 80
      targetPort: 80
