apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: cellery-system
spec:
  ports:
  - protocol: TCP
    port: 8243
    targetPort: 8243
    name: https-gw
  - protocol: TCP
    port: 9443
    targetPort: 9443
    name: https

---

apiVersion: v1
kind: Endpoints
metadata:
  name: gateway
  namespace: cellery-system
subsets:
- addresses:
  - ip: 172.17.0.2
  ports:
  - port: 8243
    name: https-gw
  - port: 9443
    name: https
