apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pet-store-controller
  namespace: default
  labels:
    app: pet-store
    service: controller
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: pet-store
        service: controller
    spec:
      containers:
        - image: celleryio/samples-pet-store-controller
          name: controller
          imagePullPolicy: IfNotPresent
          env:
            - name: CATALOG_HOST
              value: pet-store-catalog
            - name: CATALOG_PORT
              value: "80"
            - name: CUSTOMER_HOST
              value: pet-store-customers
            - name: CUSTOMER_PORT
              value: "80"
            - name: ORDER_HOST
              value: pet-store-orders
            - name: ORDER_PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pet-store-controller
  namespace: default
  labels:
    app: pet-store
    service: controller
spec:
  selector:
    app: pet-store
    service: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
